services:
  - type: web
    name: youdo-photo-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    rootDir: ./backend
    plan: free
    envVars:
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        value: youdo-photo
